executor_address_map:
  "Redis":
    - "http://ft-executor-1:8002"
  "MongoDB1":
    - "http://ft-executor-1:8002"
  "Cassandra":
    - "http://ft-executor-2:8003"

fault_tolerance_request_interval_value: 1
time_oracle_url: "http://ft-timeoracle-primary:8012/timestamp/common"
server_port: ":8081"
zipfian_constant: 0.1
latency_value: 0

redis_addr: "redis:6379"
redis_password: ""

mongodb_addr1: "mongodb://admin:password@mongodb:27017"
mongodb_username: "admin"
mongodb_password: "password"

cassandra_addr: ["cassandra:9042"]
cassandra_username: "oreo_user"
cassandra_password: "oreo_password"