version: "2"

linters:
  default: standard
  exclusions:
    warn-unused: true
    rules:
      - path: pkg/datastore/dynamodb
        linters:
          - staticcheck
    paths:
      - "_test\\.go"

formatters:
  # Enable specific formatter.
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
    - swaggo
