version: "2"

linters:
  default: standard
  exclusions:
    warn-unused: true

formatters:
  # Enable specific formatter.
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
