registry_addr: "http://localhost:9000"
time_oracle_url: "http://localhost:8009"

# Redis configuration
redis_addr: "localhost:6379"
redis_password: "kkkzoz"

# MongoDB configuration
mongodb_addr1: "mongodb://localhost:27017"
mongodb_username: "admin"
mongodb_password: "password"
